#!/bin/bash

### Functions

set_term_title(){
   echo -en "\033]0;${1}\a"
}

automount(){
  if [[ -e ${1} ]]; then
    for mnt in `ls ${1}`; do
      mount ${1}/${mnt} >/dev/null 2>&1
    done
  fi
}

ssh_agent(){
  if [[ -z ${SSH_AGENT_PID} ]]; then
    eval `ssh-agent -s`  
    ssh-add 
  fi
}

rvm_load(){
  # Load RVM into a shell session *as a function*
  [[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm" 
  [[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm
}

set_prompt(){
  PS1='\u@\h:\w\$ '
}

brew_path(){
  if [[ -x /usr/local/bin/brew ]]; then
    PATH="/usr/local/sbin:${PATH}"
  fi
}

### Variables

mount_dir='/mnt/sshfs/'
term_tile=`hostname`

### Execution

set_term_title ${term_title}
automount ${mount_dir}
set_prompt
rvm_load
ssh_agent
brew_path
