#!/bin/bash

set_term_title(){
   echo -en "\033]0;$1\a"
}

automount(){
  if [[ -e ${mntdir} ]]; then
    for mnt in `ls ${mntdir}`; do
      mount ${mntdir}/${mnt} >/dev/null 2>&1
    done
  fi
}

mntdir='/mnt/sshfs/'

set_term_title `hostname`

automount

PS1='\u@\h:\w\$ '

# Load RVM into a shell session *as a function*
[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm" 
[[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm


if [[ -z ${SSH_AGENT_PID} ]]; then
  eval `ssh-agent -s`  
  ssh-add 
fi

if [[ -x /usr/local/bin/brew ]]; then
  PATH="/usr/local/sbin:${PATH}"
fi
